config {
  type: "incremental",
  database: "comparehealthinsurance",   //Google Big Query Project ID
  schema: "analytics_326749750",            // test location; later: analytics_326749750
  name: "SessionLevelData",
  bigquery: { partitionBy: "event_date" },
  description: "Session-level aggregation (reporting layer 1). Built from GA_UnnestedData.",
 tags: ["comparehealth", "ga4_raw", "daily"] 
}

-- analytics_326749750 production sdfadasd
-- dataform testing or staging asdasdasd

pre_operations {
  ${ when(incremental(),
    `DELETE FROM ${self()}
     WHERE event_date BETWEEN CURRENT_DATE('Australia/Sydney') - 2
                          AND CURRENT_DATE('Australia/Sydney') - 1`) }
}

SELECT
  ga_session_id,
  event_date,
  user_pseudo_id,
  STRING_AGG(event_name, '|')         AS c_event_name,
  STRING_AGG(FunnelEvents, '|')       AS c_FunnelEvents,
  STRING_AGG(page_location, '|')      AS c_page_location,
  STRING_AGG(landing_page, '|')       AS c_landing_page,
  STRING_AGG(page_referrer, '|')      AS c_page_referrer,
  STRING_AGG(PageLocationLength, '|') AS c_PageLocationLength
FROM ${ref("GA_UnnestedData")}      -- ← links the graph to Model 1
WHERE event_date BETWEEN CURRENT_DATE('Australia/Sydney') - 2
                     AND CURRENT_DATE('Australia/Sydney') - 1
GROUP BY ga_session_id, event_date, user_pseudo_id 
